### ISSUE TITLE
Ads showing in stories

### ISSUE THREAD

**Issue by Mikaz-fr** [haoict/instanoads#2]
Hi,

Since one or two days there are ads showing when viewing stories. 
This wasn't the case before, can you have a look what changed on the app ?

Using Instagram 140.0.0.25.126 and InstaNoAds v0.0.2.
Please also ad releases on this github for new versions so we can tag them in issues :)

Looking forward to this awesome tweak working again.

**Comment by haoict** [comment]
Just tested with my device, Instagram 140.0, and I don't see any story ads so far.
Btw, Instagram version number only has 2 parts (138.0, 139.0, 140.0,...). How do you get a version number like 140.0.0.25.126?

**Comment by Mikaz-fr** [comment]
Hum ok, let's see if it starts to show soon for you also.
I didn't know where to get the version from so I went in the app: Settings->About->Open Source Libraries. The long version name was in the title.

**Comment by romestylez** [comment]
Same for me iPhone 8 iOS 12.4 newest IG

**Comment by haoict** [comment]
@Mikaz-fr  @romestylez 
I can confirm the issue. Today I did see ads in stories.
Seems like Instagram changed something. I'm gonna make a fix asap

**Comment by haoict** [comment]
@Mikaz-fr  @romestylez 
Hi guys,
I updated the tweak to version 1.0.1 to fix the issue
Please get it at my repo and give me feedbacks.
Thanks

**Comment by Mikaz-fr** [comment]
Working perfectly, thanks for the update. 

Please make the changelog available on the Cydia page too so people can know what changed.
